### ISSUE TITLE
CSS reachability

### ISSUE THREAD

**Issue by pierreact** [ll931217/vue-treeview#11]
Hello,

I don't know if it's a bug or my lack of knowledge. I try to override some CSS properties but can't for the tree element as it's defined like this:
#tree[data-v-58b60eba] 

I imagine data-v-58b60eba is a random ID and this will change.
If in my CSS I override #tree, it comes as #tree[data-v-anotherid].

Any idea about this?

Thank you.

**Comment by ll931217** [comment]
Hey! I remember seeing somewhere that the ID is a way to identify which component to scope to. If there is a "scoped" attribute in your style tag, then it should have the ID.

**Comment by pierreact** [comment]
Sure but the id is modified.
How should I extend/override the style with a /deep/ or a ::v-deep if I have no other way to identify it such as a class name?

If I `#tree::v-deep`, I get another tree[data-v-<id>] assigned.

What's the recommended way to override the style of vue-treeview?

Thank you.

**Comment by pierreact** [comment]
Here's an example of what I obtain:
As you can see the id is different, thus I cannot override the style of the tree.

https://ibb.co/6w94BfC

**Comment by ll931217** [comment]
Yeah the ID thing is generated whenever the file is compiled. So it will be different every time for every scope. I believe the only way to fix this is by separating the styles from the component and importing it separately. I will test this theory later when I have free time.

**Comment by pierreact** [comment]
Hey, so I have done some digging.
Seems there is not at this stage a proper solution.

As per:
https://forum.vuejs.org/t/extend-styles-and-behaviour-of-a-single-file-component/19420/2
https://github.com/vuejs/vue-loader/issues/1003

I would like to suggest the removal of the scoped statements for now here:
https://github.com/ll931217/vue-treeview/blob/master/treeview.vue#L58
https://github.com/ll931217/vue-treeview/blob/master/branch.vue#L211

Thoughts?

Of course ids and classes name collision would have to be avoided but that's not any worse than how things are usually on most projects anyway.

**Comment by ll931217** [comment]
I was thinking of removing the scopes, but I fear that other users might use the same class name or id that I do. I guess one way around that is give the root class/id name a very random string.

**Comment by pierreact** [comment]
Yes, it's what I meant by avoiding name collision.

**Comment by pierreact** [comment]
Sorry to bother you, do you have an ETA regarding this? I'd be happy to test your changes.

**Comment by ll931217** [comment]
Hey!
It should be updated now, I didn't publish it to NPM, want it to be tested further before publishing it. Clone the master branch and `npm install ../vue-treeview` or `yarn add ../vue-treeview` it. Let me know how it goes.

**Comment by pierreact** [comment]
Hello, yes, that works.
I had however to mark my overrides with `!important`.
Please let me know when you push to npm so I can use it.

THANKS A LOT!

**Comment by ll931217** [comment]
Not sure why you need to add !important since I don't have that in my code, but I'm glad it worked. Will be closing this issue as it is fixed.
