### ISSUE TITLE
About remote remote loading of category data

### ISSUE THREAD

**Issue by developerworks** [ll931217/vue-treeview#2]
I want to build a WHO [ICD-11](https://icd.who.int/browse11) tree view, does this component support data loading from remote server ?

**Comment by ll931217** [comment]
No not yet. The problem with this is that the structure of the data from remote servers can be different from what this plugin uses, so you will still need to restructure the data to fit the criteria.

**Comment by biloo-dev** [comment]
where is the problem please
![fff](https://user-images.githubusercontent.com/37638323/61398386-d066d500-a8c3-11e9-82e5-143e0333cbe5.png)

**Comment by ll931217** [comment]
Removing due to inactivity
