### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by wcheek** [ll931217/vue-treeview#27]
This component looks great. When is Vue 3 support coming?

**Comment by ll931217** [comment]
Hey @wcheek, this is something I had been thinking of doing, I am still getting to know Vue 3 syntax and I will most probably include #10 as well into the improvement

**Comment by wcheek** [comment]
@ll931217 Great - I'm looking forward to the new release!

**Comment by ll931217** [comment]
@wcheek Good news, I had been working on this the whole day and it should be out in a day or two. Just need to create tests and deploy it.

**Comment by ll931217** [comment]
#28
