### ISSUE TITLE
:editable=false doesn't allow to unfold branches

### ISSUE THREAD

**Issue by pierreact** [ll931217/vue-treeview#8]
Hello,

Thanks for the great work.
I tried to disable "editable" and found I couldn't open the branch anymore, like "Dogs" would remain closed.
Is it an expected behavior?
If so, how may I leave the whole tree open?

Thank you.

**Comment by ll931217** [comment]
Hey! Thanks for reporting this issue, I have fixed it in commit [96a90b9](https://github.com/ll931217/vue-treeview/commit/96a90b9a929360e9b50eb8271fa2ad2d3d542aaf). Please have a look

**Comment by pierreact** [comment]
@ll931217 Thank you, this fixed it.
Is there a way to get the tree fully expanded? I tried in the json to set open: "true" for each branch, doesn't work, tried also :open="true" in the template to no avail.
Any idea?

Thank you.

**Comment by ll931217** [comment]
Hello @pierreact glad it worked out. The expand all would be a new feature as it hasn't been implemented, I made a few tweaks right now, however I encountered a bug where if you collapse a child node and you try to expand all again, it wouldn't work. So I need to find a way to send that signal all the way to the proper child node.

**Comment by pierreact** [comment]
Mind to share your tweaks?

**Comment by ll931217** [comment]
Clone the master branch, then install the directory into your project.

**Comment by pierreact** [comment]
Ha, no, sorry, I meant the ones in which the tree in extended by default.

**Comment by ll931217** [comment]
There is a new prop that needs to be passed:

```vue
<treeview :tree.sync="tree" :editable="true" :expand="true" />
```

`expanded`, it takes a `boolean` value, `true` to expand all, `false` to collapse all. If you need me to fix the issue mentioned:

> 
> 
> Hello @pierreact glad it worked out. The expand all would be a new feature as it hasn't been implemented, I made a few tweaks right now, however I encountered a bug where if you collapse a child node and you try to expand all again, it wouldn't work. So I need to find a way to send that signal all the way to the proper child node.

Please let me know

**Comment by pierreact** [comment]
Hello, thanks for all this.
I tried expand and expanded as "true", neiher worked.
For my use case, I'd need it to be expanded, non collapsable.
Thanks :)

**Comment by ll931217** [comment]
Hello, did you clone the master branch onto your computer and install the clone?

```bash
git clone https://github.com/ll931217/vue-treeview.git
cd myapp
npm i ../vue-treeview
```

Your `package.json` entry for the treeview shouldn't have a version number next to the name, it should be:

    ...
    "ll931217/vue-treeview": "../vue-treeview",
    ...

Because I don't have any issues on my side, I have uploaded the latest changes in my last commit.

**Comment by pierreact** [comment]
Perfect, thank you :)

**Comment by pierreact** [comment]
Are you going to merge and publish those changes so they are available through npm repositories?

**Comment by ll931217** [comment]
Done

**Comment by pierreact** [comment]
Thank you :)
