### ISSUE TITLE
Not able to add item in empty node

### ISSUE THREAD

**Issue by chetanraskar** [ll931217/vue-treeview#9]
If you remove all nodes of 2nd node say Germany. It will not allow to add any node to Germany now. If rejects the change.

**Comment by chetanraskar** [comment]
Found solution .Was doing it wrong. Thanks

**Comment by pierreact** [comment]
@chetanraskar Not how it works, please explain how you got it working so others can benefit of the experience in case they get in the same trouble.

**Comment by chetanraskar** [comment]
@pierreact,
My  problem was I wanted to limit the dragging to the same level .And this rule has to be applied at each nesting level. For e.g. Items from level 2 should be dragged or replace only items at level 2 only. At the same time I also wanted to allow level 2 to be dragged under level1 if level 1 does not have any child.

Solution which I have used is there is event which you get on draggable :move, in which you can prevent dragging based on conditions

move
Type: Function
Required: false
Default: null

If not null this function will be called in a similar way as Sortable onMove callback. Returning false will cancel the drag operation.

function onMoveCallback(evt, originalEvent){
   ...
    // return false; — for cancel
}
evt object has same property as Sortable onMove event, and 3 additional properties:

**

- draggedContext: context linked to dragged element
- index: dragged element index
- element: dragged element underlying view model element
- futureIndex: potential index of the dragged element if the drop operation is accepted
- relatedContext: context linked to current drag operation
- index: target element index
- element: target element view model element
- list: target list
- component: target VueComponent

**
I refered below link
https://github.com/SortableJS/Vue.Draggable
